toshiba_acpi: make one-bit bitfields unsigned
BugLink: http://bugs.launchpad.net/bugs/810015

This doesn't change how the code works, but it silences a Sparse
complaint:
drivers/platform/x86/toshiba_acpi.c:121:37: error: dubious one-bit signed bitfield

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Matthew Garrett <mjg@redhat.com>
(cherry picked from commit 592b746c55b63770da25148ea3b56ed463a596b2)

Signed-off-by: Tim Gardner <tim.gardner@canonical.com>
Signed-off-by: Seth Forshee <seth.forshee@canonical.com>